using UnityEngine;
using System.IO;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Globalization;

namespace RealLifeEnvironment
{
    [System.Serializable]
    public class WorldStateSetting
    {
        public string captureName = "Capture_01";
        
        [Range(0, 24)]
        public float timeOfDay = 12f;
        public bool enableFog = true;
        public float fogDensityMultiplier = 0.0f;
        public bool heavyFogMode = false;
        public float heavyFogDensity = 0.0f;
        
        [Tooltip("Name of the season to activate (leave empty for none).")]
        public string activeSeasonName = "";
    }

    public class WorldStateCapturer : MonoBehaviour
    {
        [Tooltip("Reference to the WorldChanger component in the scene.")]
        public WorldChanger worldChanger;
        
        [Tooltip("The camera to capture from. If using post-processing, make sure the camera has the necessary components.")]
        public Camera captureCamera;

        [Header("Capture Settings")]
        public int resolutionWidth = 1920;
        public int resolutionHeight = 1080;
        [Tooltip("Folder path relative to project root.")]
        public string saveFolder = "Assets/WorldCaptures";

        [Header("Controls")]
        [Tooltip("Key to press to capture all states during play mode.")]
        public KeyCode captureKey = KeyCode.C;

        [Tooltip("Key to press to capture states from log file locations.")]
        public KeyCode captureFromLogKey = KeyCode.L;
        [Tooltip("The path to the text file generated by CameraTransformLogger.")]
        public string cameraLogFilePath = "camera_log.txt";

        [Header("States to Capture")]
        public List<WorldStateSetting> statesToCapture = new List<WorldStateSetting>();

        public static bool IsCapturing { get; private set; }

        private void Update()
        {
            if (Input.GetKeyDown(captureKey))
            {
                CaptureAll();
            }
            if (Input.GetKeyDown(captureFromLogKey))
            {
                CaptureFromLog();
            }
        }

        [ContextMenu("Capture All States")]
        public void CaptureAll()
        {
            if (IsCapturing) return;
            
            if (worldChanger == null || captureCamera == null)
            {
                Debug.LogError("WorldChanger or CaptureCamera is not assigned.", this);
                return;
            }

            if (!Directory.Exists(saveFolder))
            {
                Directory.CreateDirectory(saveFolder);
            }

            if (!Application.isPlaying)
            {
                Debug.LogError("CaptureAll must be used in Play Mode to ensure all natural rendering logic occurs properly.", this);
                return;
            }

            StartCoroutine(CaptureSequenceRoutine());
        }

        private System.Collections.IEnumerator CaptureSequenceRoutine()
        {
            IsCapturing = true;

            // Save original state
            float origTime = worldChanger.timeOfDay;
            bool origFog = worldChanger.enableFog;
            float origFogDensityMultiplier = worldChanger.fogDensityMultiplier;
            bool origHeavyFog = worldChanger.heavyFogMode;
            float origHeavyFogDensity = worldChanger.heavyFogDensity;
            
            Dictionary<string, bool> origSeasons = new Dictionary<string, bool>();
            foreach (var season in worldChanger.seasonalChanges)
            {
                origSeasons[season.seasonName] = season.isActive;
            }

            try
            {
                for (int i = 0; i < statesToCapture.Count; i++)
                {
                    var state = statesToCapture[i];
                    
                    // Apply state settings
                    worldChanger.timeOfDay = state.timeOfDay;
                    worldChanger.enableFog = state.enableFog;
                    worldChanger.fogDensityMultiplier = state.fogDensityMultiplier;
                    worldChanger.heavyFogMode = state.heavyFogMode;
                    worldChanger.heavyFogDensity = state.heavyFogDensity;

                    // Apply season settings
                    foreach (var season in worldChanger.seasonalChanges)
                    {
                        if (!string.IsNullOrEmpty(state.activeSeasonName))
                        {
                            season.isActive = season.seasonName.Equals(state.activeSeasonName, System.StringComparison.OrdinalIgnoreCase);
                        }
                        else
                        {
                            season.isActive = false;
                        }
                    }

                    // Force WorldChanger to update objects and lighting
                    worldChanger.ApplySeasonalChanges();
                    worldChanger.UpdateLighting();

                    // Wait a couple of frames for LODs, object instantiation, and rendering state to catch up
                    yield return null;
                    yield return null;

                    // Setup render texture for the capture camera
                    RenderTexture rt = new RenderTexture(resolutionWidth, resolutionHeight, 24);
                    captureCamera.targetTexture = rt;

                    // Wait for the rendering pipeline to naturally finish for this frame
                    yield return new WaitForEndOfFrame();

                    Texture2D screenShot = new Texture2D(resolutionWidth, resolutionHeight, TextureFormat.RGB24, false);
                    RenderTexture.active = rt;
                    screenShot.ReadPixels(new Rect(0, 0, resolutionWidth, resolutionHeight), 0, 0);
                    screenShot.Apply();
                    
                    captureCamera.targetTexture = null;
                    RenderTexture.active = null;
                    Destroy(rt);
                    
                    byte[] bytes = screenShot.EncodeToPNG();
                    string filename = $"{saveFolder}/{state.captureName}.png";
                    File.WriteAllBytes(filename, bytes);
                    Destroy(screenShot);
                }
                
                Debug.Log($"Successfully captured {statesToCapture.Count} states to {saveFolder}");
            }
            finally
            {
                // Restore original state
                worldChanger.timeOfDay = origTime;
                worldChanger.enableFog = origFog;
                worldChanger.fogDensityMultiplier = origFogDensityMultiplier;
                worldChanger.heavyFogMode = origHeavyFog;
                worldChanger.heavyFogDensity = origHeavyFogDensity;

                foreach (var season in worldChanger.seasonalChanges)
                {
                    if (origSeasons.TryGetValue(season.seasonName, out bool wasActive))
                    {
                        season.isActive = wasActive;
                    }
                }
                
                worldChanger.ApplySeasonalChanges();
                worldChanger.UpdateLighting();
                
                IsCapturing = false;
            }
        }

        [ContextMenu("Capture From Log")]
        public void CaptureFromLog()
        {
            if (IsCapturing) return;
            
            if (worldChanger == null || captureCamera == null)
            {
                Debug.LogError("WorldChanger or CaptureCamera is not assigned.", this);
                return;
            }

            if (!Directory.Exists(saveFolder))
            {
                Directory.CreateDirectory(saveFolder);
            }

            if (!Application.isPlaying)
            {
                Debug.LogError("CaptureFromLog must be used in Play Mode.", this);
                return;
            }

            if (!File.Exists(cameraLogFilePath))
            {
                Debug.LogError($"Camera log file not found at {cameraLogFilePath}", this);
                return;
            }

            StartCoroutine(CaptureSequenceFromLogRoutine());
        }

        private bool ParseVector3(string input, out Vector3 result)
        {
            result = Vector3.zero;
            MatchCollection matches = Regex.Matches(input, @"-?\d+([.,]\d+)?");
            if (matches.Count >= 3)
            {
                float x = float.Parse(matches[0].Value.Replace(',', '.'), CultureInfo.InvariantCulture);
                float y = float.Parse(matches[1].Value.Replace(',', '.'), CultureInfo.InvariantCulture);
                float z = float.Parse(matches[2].Value.Replace(',', '.'), CultureInfo.InvariantCulture);
                result = new Vector3(x, y, z);
                return true;
            }
            return false;
        }

        private System.Collections.IEnumerator CaptureSequenceFromLogRoutine()
        {
            IsCapturing = true;

            List<Vector3> positions = new List<Vector3>();
            List<Vector3> rotations = new List<Vector3>();

            string[] lines = File.ReadAllLines(cameraLogFilePath);
            Regex regex = new Regex(@"Position:\s*\((.*?)\)\s*\|\s*Rotation\s*\(Euler\):\s*\((.*?)\)");
            foreach (string line in lines)
            {
                Match match = regex.Match(line);
                if (match.Success)
                {
                    if (ParseVector3(match.Groups[1].Value, out Vector3 pos) && ParseVector3(match.Groups[2].Value, out Vector3 rot))
                    {
                        positions.Add(pos);
                        rotations.Add(rot);
                    }
                }
            }

            if (positions.Count == 0)
            {
                Debug.LogWarning("No valid positions found in the log file.");
                IsCapturing = false;
                yield break;
            }

            float origTime = worldChanger.timeOfDay;
            bool origFog = worldChanger.enableFog;
            float origFogDensityMultiplier = worldChanger.fogDensityMultiplier;
            bool origHeavyFog = worldChanger.heavyFogMode;
            float origHeavyFogDensity = worldChanger.heavyFogDensity;
            
            Dictionary<string, bool> origSeasons = new Dictionary<string, bool>();
            foreach (var season in worldChanger.seasonalChanges)
            {
                origSeasons[season.seasonName] = season.isActive;
            }

            Vector3 origCamPos = captureCamera.transform.position;
            Quaternion origCamRot = captureCamera.transform.rotation;

            try
            {
                for (int locIndex = 0; locIndex < positions.Count; locIndex++)
                {
                    captureCamera.transform.position = positions[locIndex];
                    captureCamera.transform.rotation = Quaternion.Euler(rotations[locIndex]);

                    yield return null;

                    for (int i = 0; i < statesToCapture.Count; i++)
                    {
                        var state = statesToCapture[i];
                        
                        worldChanger.timeOfDay = state.timeOfDay;
                        worldChanger.enableFog = state.enableFog;
                        worldChanger.fogDensityMultiplier = state.fogDensityMultiplier;
                        worldChanger.heavyFogMode = state.heavyFogMode;
                        worldChanger.heavyFogDensity = state.heavyFogDensity;

                        foreach (var season in worldChanger.seasonalChanges)
                        {
                            if (!string.IsNullOrEmpty(state.activeSeasonName))
                            {
                                season.isActive = season.seasonName.Equals(state.activeSeasonName, System.StringComparison.OrdinalIgnoreCase);
                            }
                            else
                            {
                                season.isActive = false;
                            }
                        }

                        worldChanger.ApplySeasonalChanges();
                        worldChanger.UpdateLighting();

                        yield return null;
                        yield return null;

                        RenderTexture rt = new RenderTexture(resolutionWidth, resolutionHeight, 24);
                        captureCamera.targetTexture = rt;

                        yield return new WaitForEndOfFrame();

                        Texture2D screenShot = new Texture2D(resolutionWidth, resolutionHeight, TextureFormat.RGB24, false);
                        RenderTexture.active = rt;
                        screenShot.ReadPixels(new Rect(0, 0, resolutionWidth, resolutionHeight), 0, 0);
                        screenShot.Apply();
                        
                        captureCamera.targetTexture = null;
                        RenderTexture.active = null;
                        Destroy(rt);
                        
                        byte[] bytes = screenShot.EncodeToPNG();
                        string filename = $"{saveFolder}/{state.captureName}_{locIndex}.png";
                        File.WriteAllBytes(filename, bytes);
                        Destroy(screenShot);
                    }
                }
                
                Debug.Log($"Successfully captured {statesToCapture.Count} states across {positions.Count} locations to {saveFolder}");
            }
            finally
            {
                worldChanger.timeOfDay = origTime;
                worldChanger.enableFog = origFog;
                worldChanger.fogDensityMultiplier = origFogDensityMultiplier;
                worldChanger.heavyFogMode = origHeavyFog;
                worldChanger.heavyFogDensity = origHeavyFogDensity;

                foreach (var season in worldChanger.seasonalChanges)
                {
                    if (origSeasons.TryGetValue(season.seasonName, out bool wasActive))
                    {
                        season.isActive = wasActive;
                    }
                }
                
                worldChanger.ApplySeasonalChanges();
                worldChanger.UpdateLighting();
                
                captureCamera.transform.position = origCamPos;
                captureCamera.transform.rotation = origCamRot;

                IsCapturing = false;
            }
        }
    }
}

#if UNITY_EDITOR
namespace RealLifeEnvironment
{
    using UnityEditor;

    [CustomEditor(typeof(WorldStateCapturer))]
    public class WorldStateCapturerEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();

            WorldStateCapturer capturer = (WorldStateCapturer)target;

            EditorGUILayout.Space();
            if (GUILayout.Button("Capture All States", GUILayout.Height(40)))
            {
                capturer.CaptureAll();
            }

            EditorGUILayout.Space();
            if (GUILayout.Button("Capture From Log", GUILayout.Height(40)))
            {
                capturer.CaptureFromLog();
            }
        }
    }
}
#endif
